include/cassandra: run on debian 11
debian 12 has openjdk-17, but cassandra fails with

	OpenJDK 64-Bit Server VM warning: Option UseBiasedLocking was deprecated in version 15.0 and will likely be removed in a future release.
	Unrecognized VM option 'UseConcMarkSweepGC'
	Error: Could not create the Java Virtual Machine.
	Error: A fatal exception has occurred. Program will exit.

This requires to patch the source, thus stay on debian 11 for now.

Signed-off-by: Philip Li <philip.li@intel.com>