lkp-exec/install: resolve error bundler requires Ruby version >= 2.6.0
install 2.3.26 bundler to avoid below error when ruby is < 2.6.0

	ERROR:  Error installing bundler:
		bundler requires Ruby version >= 2.6.0.
	/lkp-tests/lkp-exec/install: line 322: bundle: command not found

Signed-off-by: Philip Li <philip.li@intel.com>