distro/adaptation/debian-12: resolve 'fuse3 : Breaks: fuse'
zlib1g is already the newest version (1:1.2.13.dfsg-1).
zlib1g set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 fuse3 : Breaks: fuse
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.

Signed-off-by: Philip Li <philip.li@intel.com>