pkg/mongodb/PKGBUILD: downgrade to r6.2.0
the latest release r6.3.2 requires gcc 11.3 at least, which is only
available in debian 12 apt source. it's complicated to handle rootfs.
downgrade to r6.2.0 to successfully pack on debian 11 for now.

== fix issue ==

Detected a x86_64 processor
Checking if target OS linux is supported by the toolchain... yes
Checking if C compiler is GCC 11.3 or newer...no
Checking if C++ compiler is GCC 11.3 or newer...no
ERROR: Refusing to build with compiler that does not meet requirements
See /tmp/lkp/mongodb/src/mongo/build/scons/config.log for details

==> /tmp/stderr <==
==> ERROR: A failure occurred in build().
    Aborting...

Signed-off-by: Yujie Liu <yujie.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>