Revert "kernel-selftests: Fix userfaultfd.c:1384:37: error: 'MADV_PAGEOUT' undeclare"
This reverts commit 9cfae862098be88543bcb6f5f4359619d2af43bc.

Signed-off-by: Philip Li <philip.li@intel.com>