lib/tests/kernel-selftests-make.sh: skip sk_assign in bpf test
The test is outdated:
 $ ./test_progs-no_alu32 -vv -a sk_assign
 Switching to flavor 'no_alu32' subdirectory...
 bpf_testmod.ko is already unloaded.
 Loading bpf_testmod.ko...
 Successfully loaded bpf_testmod.ko.
 8 bytes struct bpf_elf_map fixup performed due to size mismatch!
 libbpf: loading ./test_sk_assign.o
 libbpf: elf: section(3) tc, size 1072, link 0, flags 6, type=1
 libbpf: sec 'tc': found program 'bpf_sk_assign_test' at insn offset 0 (0 bytes), code size 134 insns (1072 bytes)
 libbpf: elf: section(4) .reltc, size 32, link 27, flags 40, type=9
 libbpf: elf: section(5) maps, size 28, link 0, flags 3, type=1
 libbpf: elf: legacy map definitions in 'maps' section are not supported by libbpf v1.0+
 ERROR: opening BPF object file failed
 Unable to load program
 configure_stack:FAIL:BPF load failed; run with -vv for more info
 configure_stack: No such file or directory
 test_sk_assign:FAIL:324
 Unable to unlink /sys/fs/bpf/tc/globals/server_map: No such file or directory
 #144     sk_assign:FAIL
 Summary: 0/0 PASSED, 0 SKIPPED, 1 FAILED
 Successfully unloaded bpf_testmod.ko.

Link: https://github.com/libbpf/libbpf/wiki/Libbpf:-the-road-to-v1.0#drop-support-for-legacy-bpf-map-declaration-syntax
Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>