repo/linux/android-common: ignore 4.14 based branch
This has same reason as 677449c04307, that gcc has appeared below issue

	error: unrecognized command line option '-ftrivial-auto-var-init=pattern'

It seems that the commit a7eda6eddca5 doesn't fully backport the upstream
change,

  commit a7eda6eddca559c1c3a897a35692f9d49d46c9dd
  Date:   Tue Jun 16 10:34:35 2020 +0200

    BACKPORT: security: allow using Clang's zero initialization for stack variables

    Upstream commit f0fe00d4972a8cd4b98cc2c29758615e4d51cdfe.

which misses changes like

  +config CC_HAS_AUTO_VAR_INIT_ZERO
  +       def_bool $(cc-option,-ftrivial-auto-var-init=zero -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang)

Signed-off-by: Philip Li <philip.li@intel.com>