lkp-exec/install: update bundler version to support various ruby
Issue appears on centos 7 when doing lkp install.

Fetching: bundler-2.3.26.gem (100%)
ERROR:  Error installing bundler:
        bundler requires Ruby version >= 2.3.0.
/root/lkp-tests/lkp-exec/install: line 344: bundle: command not found

Signed-off-by: Yujie Liu <yujie.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>