sbin/make.cross: add LLVM_IAS=0 flag for powerpc arch
the default flag changed to LLVM_IAS=1 since v5.15-rc1, and will raise
below errors when compiling for powerpc arch:

error: unsupported argument '-mpower4' to option 'Wa,'
error: unsupported argument '-many' to option 'Wa,'

set LLVM_IAS=0 to disable LLVM integrated assembler and keep using GNU
assembler.

Signed-off-by: Yujie Liu <yujie.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>