include/ycsb: run on debian 11
ycsb doesn't support running under python3 with below error. Stick
to debian 11 before patching the code to run on debian 12 which has
python3 as default python.

==> /tmp/stderr <==
  File "/lkp/benchmarks/ycsb/ycsb/bin/ycsb", line 228
SyntaxError: multiple exception types must be parenthesized
  File "/lkp/benchmarks/ycsb/ycsb/bin/ycsb", line 228
    except subprocess.CalledProcessError, err:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

==> /tmp/stdout <==
preload duration: .013244664

==> /tmp/stderr <==
  File "/lkp/benchmarks/ycsb/ycsb/bin/ycsb", line 228
    except subprocess.CalledProcessError, err:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
  File "/lkp/benchmarks/ycsb/ycsb/bin/ycsb", line 228
    except subprocess.CalledProcessError, err:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    except subprocess.CalledProcessError, err:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

Signed-off-by: Philip Li <philip.li@intel.com>